# Generated by Django 4.1.3 on 2023-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='output_path',
            field=models.TextField(default='', verbose_name='输出结果保存路径'),
        ),
    ]
